export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_SIGNOUT = 'USER_SIGNOUT';

export const WINDOW_RESIZE_COUNT = 'WINDOW_RESIZE_COUNT';

export const OPEN_CLOSE_SIGNUP_POPUP = 'OPEN_CLOSE_SIGNUP_POPUP';
export const OPEN_CLOSE_LOGIN_POPUP = 'OPEN_CLOSE_LOGIN_POPUP';
export const OPEN_CLOSE_TEACHER_RATING_POPUP = 'OPEN_CLOSE_TEACHER_RATING_POPUP';

export const ALL_SUBJECT_DATA_LIST_REQUEST = 'ALL_SUBJECT_DATA_LIST_REQUEST';
export const ALL_SUBJECT_DATA_LIST_SUCCESS = 'ALL_SUBJECT_DATA_LIST_SUCCESS';

export const ALL_SCHOOL_BOARD_DATA_LIST_REQUEST = 'ALL_SCHOOL_BOARD_DATA_LIST_REQUEST';
export const ALL_SCHOOL_BOARD_DATA_LIST_SUCCESS = 'ALL_SCHOOL_BOARD_DATA_LIST_SUCCESS';

export const ALL_TEACHER_DATA_LIST_REQUEST = 'ALL_TEACHER_DATA_LIST_REQUEST';
export const ALL_TEACHER_DATA_LIST_SUCCESS = 'ALL_TEACHER_DATA_LIST_SUCCESS';
export const TEACHER_ALL_CLASS_LIST_REQUEST = 'TEACHER_ALL_CLASS_LIST_REQUEST';
export const TEACHER_ALL_CLASS_LIST_SUCCESS = 'TEACHER_ALL_CLASS_LIST_SUCCESS';
export const TEACHER_ALL_DEMO_CLASS_LIST_SUCCESS = 'TEACHER_ALL_DEMO_CLASS_LIST_SUCCESS';

export const ALL_STUDENT_DATA_LIST_REQUEST = 'ALL_STUDENT_DATA_LIST_REQUEST';
export const ALL_STUDENT_DATA_LIST_SUCCESS = 'ALL_STUDENT_DATA_LIST_SUCCESS';
export const ALL_NEW_STUDENT_PROFILE_DATA_LIST_REQUEST = 'ALL_STUDENT_DATA_LIST_REQUEST';
export const ALL_NEW_STUDENT_PROFILE_DATA_LIST_SUCCESS = 'ALL_STUDENT_DATA_LIST_SUCCESS';
export const ALL_STUDENT_SUBSCRIPTION_DATA_LIST_REQUEST = 'ALL_STUDENT_SUBSCRIPTION_DATA_LIST_REQUEST';
export const ALL_STUDENT_SUBSCRIPTION_DATA_LIST_SUCCESS = 'ALL_STUDENT_SUBSCRIPTION_DATA_LIST_SUCCESS';
export const STUDENT_ALL_CLASS_LIST_REQUEST = 'STUDENT_ALL_CLASS_LIST_REQUEST';
export const STUDENT_ALL_CLASS_LIST_SUCCESS = 'STUDENT_ALL_CLASS_LIST_SUCCESS';
export const STUDENT_ALL_TODAY_CLASS_LIST_SUCCESS = 'STUDENT_ALL_TODAY_CLASS_LIST_SUCCESS';
export const STUDENT_ALL_TIME_CLASS_LIST_SUCCESS = 'STUDENT_ALL_TIME_CLASS_LIST_SUCCESS';

export const CHAT_MODULE_ALL_STARTED_CALL = 'CHAT_MODULE_ALL_STARTED_CALL';
export const CHAT_MODULE_CURRENT_CALL_GROUP_DATA = 'CHAT_MODULE_CURRENT_CALL_GROUP_DATA';
export const CHAT_MODULE_INCOMING_CALL_GROUP_DATA = 'CHAT_MODULE_INCOMING_CALL_GROUP_DATA';
export const CHAT_MODULE_CURRENT_CALL_ALL_MEMBERS = 'CHAT_MODULE_CURRENT_CALL_ALL_MEMBERS';
export const CHAT_MODULE_NEW_USER_LEAVE_CURRENT_CALL = 'CHAT_MODULE_NEW_USER_LEAVE_CURRENT_CALL';
export const CHAT_MODULE_NEW_USER_ADDED_IN_CURRENT_CALL = 'CHAT_MODULE_NEW_USER_ADDED_IN_CURRENT_CALL';
export const CALL_SOCKET_MESSAGE_BROADCAST = 'CALL_SOCKET_MESSAGE_BROADCAST';

export const ANNOTATOR_UNDO_REDO_CAPTURE = 'ANNOTATOR_UNDO_REDO_CAPTURE';
export const GET_IP_ADDRESS = 'GET_IP_ADDRESS';
export const CAPTURE_ANNOTATOR_JSON_DATA = 'CAPTURE_ANNOTATOR_JSON_DATA';
export const ANNOTATOR_USER_ON_CAPTURE = 'ANNOTATOR_USER_ON_CAPTURE';
